const std = @import("std");

const schema = @import("schema");

pub fn emit(cli: schema.Cli, writer: *std.Io.Writer) !void {
    try writer.writeAll(
        \\// Generated by command-codegen. Do not edit.
        \\const command = @import("command");
        \\
        \\pub const cli: command.Cli = .{
        \\
    );
    try writeField(writer, 1, "name", cli.name);
    try writeOptionalField(writer, 1, "version", cli.version);
    try writeField(writer, 1, "about", cli.about);
    try writeOptionalField(writer, 1, "long_about", cli.long_about);
    try writeArgs(writer, 1, cli.args);

    try writer.writeAll("    .commands = &.{\n");
    for (cli.commands) |command| try writeCommand(writer, command);
    try writer.writeAll("    },\n};\n");
    try writer.writeAll("pub const Cli = command.Generate(&cli);\n");
}

fn writeCommand(writer: *std.Io.Writer, command: schema.Command) !void {
    try writer.writeAll("        .{\n");
    try writeField(writer, 3, "name", command.name);
    try writeField(writer, 3, "about", command.about);
    try writeOptionalField(writer, 3, "long_about", command.long_about);
    try writeArgs(writer, 3, command.args);
    try writer.writeAll("        },\n");
}

fn writeArgs(writer: *std.Io.Writer, indent: usize, args: []const schema.Arg) !void {
    try writeIndent(writer, indent);
    try writer.writeAll(".args = &.{\n");
    for (args) |arg| try writeArg(writer, indent + 1, arg);
    try writeIndent(writer, indent);
    try writer.writeAll("},\n");
}

fn writeArg(writer: *std.Io.Writer, indent: usize, arg: schema.Arg) !void {
    try writeIndent(writer, indent);
    switch (arg) {
        .positional => |value| {
            try writer.writeAll(".{ .positional = .{\n");
            try writeField(writer, indent + 1, "id", value.id);
            try writeField(writer, indent + 1, "help", value.help);
            try writeBoolField(writer, indent + 1, "required", value.required);
            try writeBoolField(writer, indent + 1, "multiple", value.multiple);
        },
        .flag => |value| {
            try writer.writeAll(".{ .flag = .{\n");
            try writeField(writer, indent + 1, "id", value.id);
            try writeOptionalField(writer, indent + 1, "short", value.short);
            try writeField(writer, indent + 1, "help", value.help);
            try writeBoolField(writer, indent + 1, "global", value.global);
            try writeBoolField(writer, indent + 1, "multiple", value.multiple);
        },
        .option => |value| {
            try writer.writeAll(".{ .option = .{\n");
            try writeField(writer, indent + 1, "id", value.id);
            try writeOptionalField(writer, indent + 1, "short", value.short);
            try writeField(writer, indent + 1, "help", value.help);
            try writeBoolField(writer, indent + 1, "required", value.required);
            try writeBoolField(writer, indent + 1, "multiple", value.multiple);
            try writeOptionalField(writer, indent + 1, "default", value.default);
            try writeBoolField(writer, indent + 1, "global", value.global);
        },
    }
    try writeIndent(writer, indent);
    try writer.writeAll("} },\n");
}

fn writeField(writer: *std.Io.Writer, indent: usize, name: []const u8, value: []const u8) !void {
    try writeIndent(writer, indent);
    try writer.print(".{s} = \"{f}\",\n", .{ name, std.zig.fmtString(value) });
}

fn writeOptionalField(
    writer: *std.Io.Writer,
    indent: usize,
    name: []const u8,
    value: ?[]const u8,
) !void {
    try writeIndent(writer, indent);
    if (value) |string| {
        try writer.print(".{s} = \"{f}\",\n", .{ name, std.zig.fmtString(string) });
    } else {
        try writer.print(".{s} = null,\n", .{name});
    }
}

fn writeBoolField(writer: *std.Io.Writer, indent: usize, name: []const u8, value: bool) !void {
    try writeIndent(writer, indent);
    try writer.print(".{s} = {},\n", .{ name, value });
}

fn writeIndent(writer: *std.Io.Writer, count: usize) !void {
    for (0..count) |_| try writer.writeAll("    ");
}
